### ISSUE TITLE
Project.getPath is deprecated.

### ISSUE THREAD

**Issue by adham90** [tombell/travis-ci-status#53] opened 2015-04-22 12:37 UTC
Use ::getPaths instead
```
Project.getPath (/opt/atom/resources/app.asar/src/project.js:583:12)
Object.isTravisProject (/home/adham/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:83:28)
<unknown> (/home/adham/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:38:7)
```

**Comment by Andersos** [comment] 2015-04-22 15:01
This is duplicate of https://github.com/tombell/travis-ci-status/issues/52

**Closed** 2015-04-22 16:57 UTC
